export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const ORDER_BY_ALPHABET = "ORDER_BY_ALPHABET";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const RESET_COUNTRIES = "RESET_COUNTRIES";
export const UPDATE_ORDER = "UPDATE_ORDER"